name: 'Linux Release Build'
on:
  push:
    branches: [ "ci-tryouts" ]
jobs:
  linux-release:
    name: Build SIL Kit TAP for Release configuration
    environment: public-github-runners
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./.github/actions/build-cmake-preset
      with:
        preset-name: linux-release
