name: 'Linux Release Build'

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux-release:
    name: Build SIL Kit TAP for Release configuration
    environment: public-github-runners
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        uses: ./.github/actions/build-cmake-preset
        with:
          preset-name: linux-release
          args:  "-D SILKIT_ADATPERS_TAG_VERSION=$GITHUB_REF_NAME"
      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          prerelease: true
          draft: true
          files: |
            _build/linux-release/SilKit-Adapters*.zip
            
          